backend:
  name: git-gateway

media_folder: uploads
publish_mode: editorial_workflow

collections:
  - name: "settings"
    label: Settings
    files:
      - name: sections
        label: Sections
        file: "data/sections.yml"
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Label, name: label, widget: string}
  - name: pages
    label: Pages
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {name: section, widget: relation, collection: settings, searchFields: name, valueField: name}
  - name: "dates"
    label: "Dates"
    folder: "_dates"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - name: events
        label: Events
        widget: list
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Start Date", name: "start_date", widget: "date"}
  - name: blog
    label: Blog
    folder: a/b/c
    create: true
    fields:
      - {label: Title, name: title}
      - {label: List, name: list, widget: list, required: false, fields: [{label: List Child, name: list_child}]}
  - name: stuff
    label: Stuff
    files:
      - name: stuff
        label: Stuff
        file: stuff/stuff.json
        fields:
          - label: Entries
            name: entries
            widget: list
            fields:
              - {label: Title, name: title, widget: title}
              - {label: Date, name: date, widget: datetime}
              - {label: Body, name: body, widget: markdown}
