backend:
  name: git-gateway

media_folder: uploads
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: a/b/c
    fields:
      - {label: Title, name: title}
  - name: stuff
    label: Stuff
    files:
      - name: stuff
        label: Stuff
        file: stuff/stuff.json
        fields:
          - label: Entries
            name: entries
            widget: list
            fields:
              - {label: Title, name: title, widget: title}
              - {label: Date, name: date, widget: datetime}
              - {label: Body, name: body, widget: markdown}
