backend:
  name: github
  repo: erquhart/personal-site

media_folder: uploads

collections:
  - name: stuff
    label: Stuff
    files:
      - name: stuff
        label: Stuff
        file: stuff/stuff.json
        fields:
          - label: Entries
            name: entries
            widget: list
            fields:
              - {label: Title, name: title, widget: title}
              - {label: Date, name: date, widget: datetime}
              - {label: Body, name: body, widget: markdown}
