backend:
  name: github
  repo: erquhart/notes

media_folder: assets

collections:
  - name: notes
    label: Notes
    folder: notes
    fields:
      - {label: Title, name: title}
      - {label: Date, name: date, widget: datetime}
      - {label: Body, name: body, widget: markdown}
