backend:
  name: github
  repo: erquhart/personal-site

media_folder: assets

collections:
  - name: pages
    label: Pages
    files:
      - name: home
        label: Home
        file: src/index.json
        fields:
          - {label: Name, name: name}
          - {label: Profile Image, name: profile-image, widget: image}
          - {label: Heading, name: heading}
          - label: Position
            name: position
            widget: object
            fields:
              - {name: title, label: Title}
              - {name: link_address, label: Link Address}
              - {name: link_text, label: Link Text}
          - name: recent_work
            label: Recent Work
            widget: list
            fields:
              - {name: heading, label: Heading}
              - {name: description, label: Description}
              - {name: link_address, label: Link Address}
      - name: stuff
        label: Stuff
        file: src/stuff/stuff.json
        fields:
          - label: Entries
            name: entries
            widget: list
            fields:
              - {label: Title, name: title, widget: title}
              - {label: Date, name: date, widget: datetime}
              - {label: Body, name: body, widget: markdown}
