backend:
  name: github
  repo: erquhart/personal-site

media_folder: assets

collections:
  - name: pages
    label: Pages
    files:
      - name: home
        label: Home
        file: src/index.json
        fields:
          - {label: Profile Image, name: profile-image, widget: image}
      - name: stuff
        label: Stuff
        file: src/stuff/stuff.json
        fields:
          - label: Entries
            name: entries
            widget: list
            fields:
              - {label: Title, name: title, widget: title}
              - {label: Date, name: date, widget: datetime}
              - {label: Body, name: body, widget: markdown}
